### ISSUE TITLE
Code sample for @dash4/react-xterm doesn't work?

### ISSUE THREAD

**Issue by bduffany** [smollweide/dash4#8]
The code sample on [NPM](https://www.npmjs.com/package/@dash4/react-xterm) for react-xterm doesn't seem to be working.

https://codesandbox.io/s/elastic-snyder-kqf9v?file=/src/App.tsx

Am I missing something?

**Comment by smollweide** [comment]
Hi @bduffany,

you just missed to import the css:

```
import "@dash4/react-xterm/lib/ReactXterm.css";
```

**Comment by bduffany** [comment]
Thanks!

Is there anything else that needs to be done to get the terminal working so that users can type into it?

**Comment by smollweide** [comment]
At best you take a look at Zeit‘s hyper project. This package is build for read only or better limited access because of security reasons. If you use it in browser with full write access you should make sure you don’t end up with a security issue.

This package is used in Dash4 you can take a look on how it is integrated there and how to give limited access to the underling process. 

[Hyper](https://github.com/zeit/hyper)
[Dash4](https://github.com/smollweide/dash4)

**Comment by smollweide** [comment]
Can you explain what your plan is?
I used [node-pty](https://github.com/Microsoft/node-pty) for the underlining process and deliver its output via websocket to @dash4/react-xterm. By using this approach you need to send the users input (there is an Textarea available) to the node-pty process. Which will then send it back to the client.

Sending the user input to the backend process: 
https://github.com/smollweide/dash4/blob/master/plugins/plugin-terminal/src/client/index.tsx#L119

Process the user input:
https://github.com/smollweide/dash4/blob/master/plugins/plugin-terminal/src/server/index.ts#L170

I hope this was helpful for you.
Happy coding :)

**Comment by bduffany** [comment]
@smollweide thanks so much for the links!

Come to think of it, I came across `@dash4/react-xterm` thinking of implementing something similar to dash4! I was hoping to have some way to run multiple terminals at once, in order to spin up a full dev stack on the local machine, but I didn't like the user experience of GNU screen / tmux / ncurses etc... I wanted some UI that allows viewing the live logs for each command and possibly some UI buttons to quickly send signals and execute commands. dash4 seems like it is well on the way to accomplishing this dream! Maybe I'll take a look through the source code and see if I have any ideas for improvement.

Cheers!

**Comment by smollweide** [comment]
Thank you :)

Yes that is exactly what Dash4 does. It runs in the browser and starts multiple processes. I build it because it solves the problem with a lot of different tasks running, especially in Monorepo‘s. You can configure what tasks should be started automatically and which not. The config can be shared by adding it to the repo. Also Dash4 is build with an Plugin System which allowed you to write your own plugin to solve specific things.

I would be happy if you could take a look on and of cause even more if you are willing to contribute.

Greetings
